# Файл: .streamlit/secrets.toml
API_USERNAME = "rvl_testapi"
API_PASSWORD = "rvltestapi2024"

# PostgreSQL
PG_HOST = "188.246.226.234"
PG_PORT = "5432"
PG_DB = "drain_feedback"
PG_USER = "drain_app"
PG_PASSWORD = "Vic090172"